---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  # blead and dev don't play nicely with Module::Build
  #- blead
  #- dev
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
    - perl: dev
    - env: COVERAGE=1 HARNESS_OPTIONS=j1
      perl: "5.28"
  fast_finish: 1
  include:
    - env: COVERAGE=1 HARNESS_OPTIONS=j1
      perl: "5.28"
env:
  global:
    - AUTHOR_TESTING=1
    - CPAN_MIRROR=https://cpan.metacpan.org/
    - HARNESS_OPTIONS='j:c'
    - RELEASE_TESTING=1
script:
  - ./Build authortest
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm --notest App::cpm
  - cpm install --global CPAN::Meta
  - perl Build.PL
install:
  - cpm install --global --notest --workers 2 Perl::Critic::More Test::Perl::Critic Devel::EnforceEncapsulation PPI Test::Memory::Cycle PPIx::QuoteLike Test::Kwalitee
  - cpan-install --deps # installs prereqs, including recommends
  - cpan-install --coverage # installs coverage prereqs, if enabled
before_script:
  - coverage-setup
after_success:
  - coverage-report
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - andy@petdance.com
  irc:
    channels:
      - irc.perl.org#perlcritic
    template:
      - "%{branch}: %{message} %{build_url}"
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
