language: perl

perl:
   - "5.21"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

notifications:
   on_success: change
   #on_success: always
   on_failure: always
   irc:
      channels:
         - "irc.perl.org#perlcritic"
      template:
         - "%{branch}: %{message} %{build_url}"
   #email: false

install:
   - cpanm Perl::Critic::More Devel::EnforceEncapsulation
   - sudo apt-get install -qq aspell

script:
   - export HARNESS_OPTIONS='j:c'
   - perl Build.PL
   - ./Build authortest
